# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: StackOverflowNER-NS
short_description: Continual learning for named entity recognition (NER) using the StackOverflowNER dataset.
description: challenge_details/description.html
evaluation_details: challenge_details/evaluation_details.html
terms_and_conditions: challenge_details/terms_and_conditions.html
image: logo.jpg
submission_guidelines: challenge_details/submission_guidelines.html
leaderboard_description: F1 Score on Test (All 5 Episodes)
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2021-11-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Ep. 1", "Ep. 2", "Ep. 3", "Ep. 4", "Ep. 5", "Average"],
        "default_order_by": "Average",
      }

challenge_phases:
  - id: 1
    name: Test Phase
    description: challenge_details/challenge_phase_1_description.html
    leaderboard_public: True
    is_public: True
    is_submission_public: True
    start_date: 2021-11-01 00:00:00
    end_date: 2099-04-25 23:59:59
    test_annotation_file: annotations/test_annotation.json
    codename: test
    max_submissions_per_day: 5
    max_submissions_per_month: 15
    max_submissions: 15

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
